[colors]
background = '#fdf6e3'
foreground = '#657b83'
selection-background = '#eee8d5'
selection-foreground = '#586e75'
cursor = '#657b83'
black = '#073642'
red = '#dc322f'
green = '#859900'
yellow = '#b58900'
blue = '#268bd2'
magenta = '#d33682'
cyan = '#2aa198'
white = '#eee8d5'
light-black = '#002b36'
light-red = '#cb4b16'
light-green = '#586e75'
light-yellow = '#657b83'
light-blue = '#839496'
light-magenta = '#6c71c4'
light-cyan = '#93a1a1'
light-white = '#fdf6e3'

tabs = '#eee8d5'
tabs-active = '#93a1a1'
