#!/usr/bin/env sh

#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

MAIN_DISPLAY=$(system_profiler SPDisplaysDataType | grep -B 3 'Main Display:' | awk '/Display Type/ {print $3}')

if [[ $MAIN_DISPLAY = "Built-in" ]]; then
    yabai -m config external_bar main:0:0
else
    yabai -m config external_bar main:36:0
fi

config=(
    # global settings
    mouse_follows_focus          on
    focus_follows_mouse          autoraise
    window_placement             second_child
    window_shadow                off
    window_opacity               off
    window_opacity_duration      0.0
    active_window_opacity        1.0
    normal_window_opacity        0.90
    insert_feedback_color        0xff268bd2
    split_ratio                  0.50
    auto_balance                 off
    mouse_modifier               alt
    mouse_action1                move
    mouse_action2                resize
    mouse_drop_action            swap

    # general space settings
    layout                       bsp
    top_padding                  16
    bottom_padding               16
    left_padding                 16
    right_padding                16
    window_gap                   12

    # bar integration
    external_bar                 all:36:0
)
yabai -m config "${config[@]}"

echo "yabai configuration loaded..."

borders active_color=0xddcb4b16 inactive_color=0x00cb4b16 width=6.0 &

# 
